fix: validate testing

diff --git a/.github/workflows/validate.yaml b/.github/workflows/validate.yaml
--- a/.github/workflows/validate.yaml
+++ b/.github/workflows/validate.yaml
@@ -43,25 +43,26 @@ jobs:
       - name: Install Terragrunt
         run: |
           curl -s -qL -o terragrunt https://github.com/gruntwork-io/terragrunt/releases/download/${{ env.TG_VERSION }}/terragrunt_linux_amd64
-            if [ $? -ne 0 ]; then
-              echo "Failed to download Terragrunt"
-              exit 1
-            fi
-            chmod +x terragrunt
-            if [ $? -ne 0 ]; then
-              echo "Failed to make Terragrunt executable"
-              exit 1
-            fi
-            sudo mv terragrunt /usr/local/bin
-            if [ $? -ne 0 ]; then
-              echo "Failed to move Terragrunt to /usr/local/bin"
-              exit 1
-            fi
-            terragrunt --version
-            if [ $? -ne 0 ]; then
-              echo "Terragrunt installation failed"
-              exit 1
-            fi
+          ls
+          if [ $? -ne 0 ]; then
+            echo "Failed to download Terragrunt"
+            exit 1
+          fi
+          chmod +x terragrunt
+          if [ $? -ne 0 ]; then
+            echo "Failed to make Terragrunt executable"
+            exit 1
+          fi
+          sudo mv terragrunt /usr/local/bin
+          if [ $? -ne 0 ]; then
+            echo "Failed to move Terragrunt to /usr/local/bin"
+            exit 1
+          fi
+          terragrunt --version
+          if [ $? -ne 0 ]; then
+            echo "Terragrunt installation failed"
+            exit 1
+          fi
       
       - name: Verify Terragrunt version
         run: terragrunt --version
